import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=' bg-slate-200 h-screen'>
      <Head>
        <title>My Portfolio</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.png" />
      </Head>

      <nav className='flex justify-between  mx-8 sm:mx-11 lg:mx-20 xl:mx-28 '>
        <div className='text-slate-900 py-2 lg:py-4 font-medium text-xl md:text-2xl text-center uppercase'>
          Mehedi Hasan
        </div>
        <ul className='w-1/2 font-normal text-center flex justify-end uppercase text-lg text-slate-100'>
          <li className='sm:bg-gray-400 cursor-pointer bg-slate-900 px-8 py-2 lg:px-12 lg:py-4 hover:bg-slate-700 duration-150 backdrop-blur-md '>Home</li>
          <li className='cursor-pointer bg-slate-900 px-8 py-2 lg:px-12 lg:py-4 hover:bg-slate-700 duration-150 backdrop-blur-md '>About</li>
          <li className='cursor-pointer bg-slate-900 px-8 py-2 lg:px-12 lg:py-4 hover:bg-slate-700 duration-150 backdrop-blur-md '>Contact</li>
        </ul>
      </nav>
    </div>
  )
}
