import Head from 'next/head'
import { useEffect, useState } from 'react'
import Footer from '../components/index/Footer'
import Nav from '../components/index/Nav'
import ClienForm from '../components/index/ClientForm'
import MyWork from '../components/index/MyWork'
import Skills from '../components/index/Skills'
import Main from '../components/index/Main'
import Experience from '../components/index/Experience'

export default function Home() {

  const [showClientForm, setShowClientForm] = useState(false);
  const [changeTheme, setChangeTheme] = useState(false);


  //check browser have local storage 
  useEffect(() => {
    const theme = JSON.parse(localStorage.getItem('theme'));

    if (['light'].includes(theme)) return setChangeTheme(() => false);
    if (['dark'].includes(theme)) return setChangeTheme(() => true);

    if (typeof window !== "undefined") {
      if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
        setChangeTheme(() => true)
      }
      else {
        setChangeTheme(() => false)
      }
    }

  }, [])

  return (
    <div className={`${!changeTheme ? ' ' : 'dark '} ${showClientForm ? ' fixed ' : ' '} bg-slate-50  min-h-fit scroll-smooth duration-200`}>
      <Head>
        <title>My Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/* Form for client information */}
      {showClientForm ? <ClienForm setShowClientForm={setShowClientForm} /> : ''}

      {/* Nav bar component */}
      <Nav changeTheme={changeTheme} setChangeTheme={setChangeTheme} />

      {/* front page */}
      <div id='home' className='duration-300 dark:bg-slate-900'><Main /></div>

      {/* About my skills */}
      <div id='skills' className=' dark:bg-slate-900'><Skills /></div>

      {/* Experience section */}
      <div id='experience' className='max-w-screen overflow-hidden dark:bg-slate-900'><Experience /></div>

      {/* Projects  */}
      <div id='projects' className='dark:bg-slate-900'><MyWork /></div>

      {/* footer area */}
      <div id='message' className='dark:bg-slate-900'><Footer id='#contact' setShowClientForm={setShowClientForm} /></div>
    </div>
  )
}
